fixes #11 Better testing of security for authorize call, test that OA…
NationalSecurityAgency/datawave-authorization-service pull request #12
Opened 2020-12-02 16:12 UTC by billoley

…uth calls do not enforce allowedCallers

2020-12-10 15:36 UTC, keith-ratcliffe approved these changes, later dismissed

2020-12-16 15:01 UTC, billoley commented
The idea here is that we want to bypass the allowedCallers check for enpoints with an oauth path prefix in the authorization service.  The OAuth feature has its own security with client_id, client_secret, redirects, and time limitations.  We are attempting to limit the impact of the changes to the authorization service.

The AllowedCallersFilter is already subclassed as the AuthorizationAllowedCallersFilter.  This filter is executed before the spring X509AuthenticationFilter and will only check for allowedCallers if there is a client certificate.  The AuthorizationAllowedCallersFilter  bypasses this check for paths with an oauth prefix.

After that, if there is a JWT Bearer token in the Authorization HttpHeader, then that is used and there is no allowedCallers check

After that, the AuthorizationProxiedEntityX509Filter is executed.  If authorization has not already hapened (JWT), then the configured UserDetailsService is involed.  In the case of the Authorization servivce, this is the ProxiedEntityUserDetailsService.  There is a check for allowedCallers in that class, but it does not have access to the HttpServletRequest (to check the path for oauth).  To fix this, AuthorizationProxiedEntityX509Filter @Overrides getPreAuthenticatedPrincipal() to call super.getPreAuthenticatedPrincipal() to get a ProxiedEntityPreauthPrincipal and then if non-null create a subclass AuthorizationProxiedEntityPreauthPrincipal which contains the HttpServletRequest .   ProxiedEntityUserDetailsService can then call a static method on AuthorizationAllowedCallersFilter to determine if it should check for allowedCallers for that request.

2020-12-18 17:34 UTC, keith-ratcliffe requested changes
I think this looks good. It would be nice to capture some of your PR comment in javadoc though, for future generations ;) AuthorizationSecurityConfigurer might be a good place for that(?)... the current javadoc there covers several use cases already but nothing about the new oauth stuff

2021-01-05 18:24 UTC, keith-ratcliffe approved these changes

2021-01-05 19:46 UTC, merged